module.exports = {
    createDB: 'CREATE DATABASE IF NOT EXISTS BUILDING;',
    setDB: 'USE BUILDING',
    createTableUser: `CREATE TABLE IF NOT EXISTS USER (
        ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        USERNAME VARCHAR(20) NOT NULL,
        PLATE VARCHAR(7) NOT NULL UNIQUE,
        PASSWORD CHAR(32) NOT NULL,
        REVISED BOOLEAN DEFAULT FALSE NOT NULL
    ) ENGINE=InnoDB;`,
    createTableSensor: `CREATE TABLE IF NOT EXISTS SENSOR (
        ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        AT DATETIME
    ) ENGINE=InnoDB;`,
}
