module.exports = {
    createDB: 'CREATE DATABASE IF NOT EXISTS BUILDING;',
    setDB: 'USE BUILDING',
    createTableUser: `CREATE TABLE IF NOT EXISTS USER (
        ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        USERNAME VARCHAR(20) NOT NULL UNIQUE,
        PLATE VARCHAR(7) NOT NULL UNIQUE,
        PASSWORD CHAR(32) NOT NULL,
        REVISED BOOLEAN DEFAULT FALSE NOT NULL
    ) ENGINE=InnoDB;`,
    createTableSensor: `CREATE TABLE IF NOT EXISTS SENSOR (
        ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        AT DATETIME
    ) ENGINE=InnoDB;`,
    createTableDetections: `CREATE TABLE IF NOT EXISTS DETECTIONS (
        ID INT PRIMARY KEY,
        TRUE_DETECTION INT NOT NULL,
        FALSE_DETECTION INT NOT NULL,
        BELONG INT NOT NULL,
        NOT_BELONG INT NOT NULL
    ) ENGINE=InnoDB;`,
    initialTableDetections: `INSERT IGNORE INTO DETECTIONS VALUES (0,0,0,0,0)`
}
